# contraints file (.xdc file) for lab 4

# Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]
    set_property IOSTANDARD LVCMOS33 [get_ports clk]

create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]


#Buttons
set_property PACKAGE_PIN U18 [get_ports load]
    set_property IOSTANDARD LVCMOS33 [get_ports load]
set_property PACKAGE_PIN T17 [get_ports cycle]
    set_property IOSTANDARD LVCMOS33 [get_ports cycle]    

#7-seg display
set_property PACKAGE_PIN V7 [get_ports {display[0]} ]
    set_property IOSTANDARD LVCMOS33 [get_ports {display[0]} ]
set_property PACKAGE_PIN W7 [get_ports {display[7]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {display[7]}]
set_property PACKAGE_PIN W6 [get_ports {display[6]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {display[6]}]
set_property PACKAGE_PIN U8 [get_ports {display[5]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {display[5]}]
set_property PACKAGE_PIN V8 [get_ports {display[4]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {display[4]}]
set_property PACKAGE_PIN U5 [get_ports {display[3]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {display[3]}]
set_property PACKAGE_PIN V5 [get_ports {display[2]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {display[2]}]
set_property PACKAGE_PIN U7 [get_ports {display[1]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {display[1]}]
set_property PACKAGE_PIN U2 [get_ports {anode[0]} ]
    set_property IOSTANDARD LVCMOS33 [get_ports {anode[0]}]
set_property PACKAGE_PIN U4 [get_ports {anode[1]} ]
    set_property IOSTANDARD LVCMOS33 [get_ports {anode[1]}]
set_property PACKAGE_PIN V4 [get_ports {anode[2]} ]
    set_property IOSTANDARD LVCMOS33 [get_ports {anode[2]} ]
set_property PACKAGE_PIN W4 [get_ports {anode[3]} ]
    set_property IOSTANDARD LVCMOS33 [get_ports {anode[3]} ]
   
#Switches
set_property PACKAGE_PIN V17 [get_ports {angle[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {angle[0]}]
set_property PACKAGE_PIN V16 [get_ports {angle[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {angle[1]}]
set_property PACKAGE_PIN W16 [get_ports {angle[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {angle[2]}]
set_property PACKAGE_PIN W17 [get_ports {angle[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {angle[3]}]
set_property PACKAGE_PIN W15 [get_ports {angle[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {angle[4]}]
set_property PACKAGE_PIN V15 [get_ports {angle[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {angle[5]}]
set_property PACKAGE_PIN W14 [get_ports {angle[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {angle[6]}]
set_property PACKAGE_PIN W13 [get_ports {angle[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {angle[7]}]
set_property PACKAGE_PIN V2 [get_ports {angle[8]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {angle[8]}]
set_property PACKAGE_PIN T3 [get_ports {angle[9]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {angle[9]}]
set_property PACKAGE_PIN T2 [get_ports {angle[10]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {angle[10]}]
set_property PACKAGE_PIN R3 [get_ports {angle[11]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {angle[11]}]
set_property PACKAGE_PIN W2 [get_ports {angle[12]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {angle[12]}]
set_property PACKAGE_PIN U1 [get_ports {angle[13]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {angle[13]}]
set_property PACKAGE_PIN T1 [get_ports {angle[14]}]  
    set_property IOSTANDARD LVCMOS33 [get_ports {angle[14]}]
set_property PACKAGE_PIN R2 [get_ports {angle[15]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {angle[15]}]